FROM mcr.microsoft.com/devcontainers/python:3.11

RUN wget -qO /usr/local/bin/websocat https://github.com/vi/websocat/releases/latest/download/websocat.x86_64-unknown-linux-musl && \
    chmod a+x /usr/local/bin/websocat

